parameters:
#    application_fos_knp_paginator.example.class: Application\FOS\KnpPaginatorBundle\Example

services:
#    application_fos_knp_paginator.example:
#        class: %application_fos_knp_paginator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
