
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_project_user:
    resource: '@SonataUserBundle/Resources/config/routing/profile.xml'
#Sonata Admin Bundle routes import
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}
    defaults: { _locale: %locale% }
    requirements:
        _locale:  en|tr|ru

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile/
    defaults: { _locale: %locale% }
    requirements:
        _locale:  en|tr|ru

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register/
    defaults: { _locale: %locale% }
    requirements:
        _locale:  en|tr|ru

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting/
    defaults: { _locale: %locale% }
    requirements:
        _locale:  en|tr|ru

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password/

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

application_sonata_user:
    type: rest
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/routing.yml"
    prefix: /{_locale}
    defaults: { _locale: en }
    requirements:
        _locale:  en|tr|ru

podorozhniki_main:
    resource: "@PodorozhnikiMainBundle/Resources/config/routing.yml"

_security_check_facebook:
    pattern:   /facebook/login_check
    defaults:  { _controller: ApplicationSonataUserBundle:User:loginFb }

_security_facebook_logout:
  pattern:  /facebook/logout

user_couple_fb_with_account:
    pattern: /user/couple/facebook
    defaults: { _controller: ApplicationSonataUserBundle:User:connectFacebookWithAccount }

facebook:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

podorozhniki_rides_rest:
    type: rest
    resource: Podorozhniki\MainBundle\Controller\RidesController
    prefix: /{_locale}
    defaults: { _locale: %locale% }
    requirements:
        _locale:  en|tr|ru
