<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use FOS\MessageBundle\Model\ParticipantInterface;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser implements ParticipantInterface
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $rides;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
        $this->rides = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add rides
     *
     * @param \Podorozhniki\MainBundle\Entity\Ride $rides
     * @return User
     */
    public function addRide(\Podorozhniki\MainBundle\Entity\Ride $rides)
    {
        $this->rides[] = $rides;

        return $this;
    }

    /**
     * Remove rides
     *
     * @param \Podorozhniki\MainBundle\Entity\Ride $rides
     */
    public function removeRide(\Podorozhniki\MainBundle\Entity\Ride $rides)
    {
        $this->rides->removeElement($rides);
    }

    /**
     * Get rides
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRides()
    {
        return $this->rides;
    }

    public function setEmail($email)
    {
        parent::setEmail($email);
        $this->setUsername($email);
    }



    protected $facebookUid;

    public function serialize()
    {
        return serialize(array($this->facebookUid, parent::serialize()));
    }

    public function unserialize($data)
    {
        list($this->facebookUid, $parentData) = unserialize($data);
        parent::unserialize($parentData);
    }


    /**
     * Get the full name of the user (first + last name)
     * @return string
     */
    public function getFullName()
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }

    /**
     * @param string $facebookUid
     * @return void
     */
    public function setFacebookUid($facebookUid)
    {
        $this->facebookUid = $facebookUid;
        $this->setUsername($facebookUid);
    }

    /**
     * @return string
     */
    public function getFacebookUid()
    {
        return $this->facebookUid;
    }

    /**
     * @param Array
     */
    public function setFBData($fbdata)
    {
        if (isset($fbdata['id'])) {
            $this->setFacebookUid($fbdata['id']);
            $this->addRole('ROLE_FACEBOOK');
        }
        if (isset($fbdata['first_name'])) {
            $this->setFirstname($fbdata['first_name']);
        }
        if (isset($fbdata['last_name'])) {
            $this->setLastname($fbdata['last_name']);
        }
        if (isset($fbdata['email'])) {
            $this->setEmail($fbdata['email']);
        }
        if(isset($fbdata['birthday'])){

            $this->setDateOfBirth(new \DateTime($fbdata['birthday']));
        }
    }
    /**
     * @var integer
     */
    private $likes;

    /**
     * @var integer
     */
    private $dislikes;

    /**
     * @var integer
     */
    private $points;

    /**
     * Set likes
     *
     * @param integer $likes
     * @return User
     */
    public function setLikes($likes)
    {
        $this->likes = $likes;
    
        return $this;
    }

    /**
     * Get likes
     *
     * @return integer 
     */
    public function getLikes()
    {
        return $this->likes;
    }

    /**
     * Set dislikes
     *
     * @param integer $dislikes
     * @return User
     */
    public function setDislikes($dislikes)
    {
        $this->dislikes = $dislikes;
    
        return $this;
    }

    /**
     * Get dislikes
     * @return integer
     */
    public function getDislikes()
    {
        return $this->dislikes;
    }

    /**
     * Set points
     * @param integer $points
     * @return User
     */
    public function setPoints($points)
    {
        $this->points = $points;

        return $this;
    }

    /**
     * Get points
     * @return integer
     */
    public function getPoints()
    {
        return $this->points;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $messages;


    /**
     * Add messages
     *
     * @param \Application\FOS\MessageBundle\Entity\Message $messages
     * @return User
     */
    public function addMessage(\Application\FOS\MessageBundle\Entity\Message $messages)
    {
        $this->messages[] = $messages;
    
        return $this;
    }

    /**
     * Remove messages
     *
     * @param \Application\FOS\MessageBundle\Entity\Message $messages
     */
    public function removeMessage(\Application\FOS\MessageBundle\Entity\Message $messages)
    {
        $this->messages->removeElement($messages);
    }

    /**
     * Get messages
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMessages()
    {
        return $this->messages;
    }

}