parameters:
#    application_fos_message.example.class: Application\FOS\MessageBundle\Example

services:
#    application_fos_message.example:
#        class: %application_fos_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
